### ISSUE TITLE
Bug(s)

### ISSUE THREAD

**Issue by Ultracane1997** [starfrost013/TrackMaker#1]
Hello, you might already be aware for some but I will try to list as many bugs/issues that I can possibly come across:
- Basin maps are not working.
- The layers are not working much at all, very limited at the moment.
- Some of the text is white or invisible when trying to add a new storm as well.

I will follow up with some more bugs as I come across them.

**Comment by starfrost013** [comment]
Development of this has ceased, so will be closing this bug
